# Generated by Django 4.2.5 on 2023-09-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
